default: &default
  adapter: postgresql
  host: localhost
  database: blackbits_development

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: blackbits
  username: "root"
  password: "herpityderpityderp!"
