Forum.create(title: "Announcements", description: "Forum announcements.")
Forum.create(title: "Love Advice", description: "General Relationship discussion. Post your problems and let other members help you out.")
Forum.create(title: "Ask A Male", description: "Wonder what your guy friend is thinking? Find help from our male members.")
Forum.create(title: "Ask A Female", description: "Wonder what your girl friend is thinking? Find help from our female members.")
Forum.create(title: "Intimate Forum", description: "Discussion related to close body contact & related issues.")
Forum.create(title: "Off-Topic Discussion", description: "Forum for general conversation and anything not related to the other forums.")
